### ISSUE TITLE
Résolution appareil photo full screen camera

### ISSUE THREAD

**Issue by Tboy70** [ChristopheBoucaut/customCamera#17]
Sur certains appareil photo, la résolution n'est pas assez bonne pour mettre la camera en plein écran.

**Comment by Tboy70** [comment]
Si je comprends ce qu'il faut faire : detecter resolution appareil, résolution écran et si l'un est plus petit que l'autre, on rempli de noir. (jerome)

**Comment by ChristopheBoucaut** [comment]
fixed by #47
