### ISSUE TITLE
Problème preview avec certaines tablettes

### ISSUE THREAD

**Issue by Tboy70** [ChristopheBoucaut/customCamera#40]
Quand on teste l'application avec la tablette de Jérôme (blanche) : 
_ On prend la photo -> OK
_ Les bouton accepter/refuser s'affiche -> OK
_ L'aperçu de la photo ne s'affiche pas -> PROBLÈME
_ Mais, en tournant l'appareil, l'aperçu s'affiche

**Comment by ChristopheBoucaut** [comment]
fixed by #51
